labels: []
body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Share Your Idea
        
        Ideas that get implemented earn +25 bonus karma!
        
  - type: textarea
    id: idea
    attributes:
      label: The Idea
      description: What would you like to see in the game?
      placeholder: "I think we should add..."
    validations:
      required: true
      
  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Gameplay Mechanic
        - Visual/UI
        - New Level Type
        - Achievement
        - Social Feature
        - Documentation
        - Other
    validations:
      required: true
      
  - type: textarea
    id: benefit
    attributes:
      label: Why is this valuable?
      description: How does this improve the game?
      placeholder: "This would make the game better because..."
    validations:
      required: true
      
  - type: input
    id: guardian
    attributes:
      label: Guardian Answer
      description: Who is the First Guardian? (proof of humanity)
      placeholder: "The answer is..."
    validations:
      required: true
